AllCops:
  DisplayCopNames: true
Metrics/BlockLength:
  Exclude:
    - "**/**/*_spec.rb"
Metrics/ClassLength:
  Max: 200
Metrics/LineLength:
  Max: 280
Metrics/MethodLength:
  Max: 30
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/BlockDelimiters:
  Enabled: false
# enable Style/PredicateName as part of ruby_aem v2
Style/PredicateName:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
